package com.bank.onboarding.services;

import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

import com.bank.onboarding.dto.OrinocoCasePayload;
import com.bank.onboarding.util.RestClientUtilDummy;

import lombok.extern.slf4j.Slf4j;

@Slf4j
@Service
public class OrinocoCaseManagementService {

    private final RestClientUtilDummy restClientUtil;

    @Autowired
    public OrinocoCaseManagementService(RestClientUtilDummy restClientUtil) {
        this.restClientUtil = restClientUtil;
    }

    /**
     * Notify the back office through Orinoco Case Management API.
     *
     * @param requestContext The complete request context
     * @param errorMessage The error message describing the failure
     * @return Case ID generated by the system
     */
    public String notifyBackOffice(Map<String, Object> requestContext, String errorMessage) {
        // Dynamically create Orinoco Case Payload
        OrinocoCasePayload casePayload = OrinocoCasePayload.createFromContext(requestContext, errorMessage);

        log.info("Notifying Orinoco Case Management system with payload: {}", casePayload);

        try {
            // Call the Orinoco Case Management API to notify the back office
            ResponseEntity<String> response = restClientUtil.makeCaseManagementCall(
                "https://orinoco.api/case-management",
                Map.of("case", casePayload)
            );

            if (response.getStatusCode().is2xxSuccessful()) {
                log.info("Successfully notified the Orinoco Case Management system. Case ID: {}", casePayload.getCaseId());
                return casePayload.getCaseId();
            } else {
                log.error("Failed to notify the Orinoco Case Management: {}", response.getBody());
                return "ERROR-CASE";
            }

        } catch (Exception ex) {
            log.error("Error occurred while notifying Orinoco Case Management: {}", ex.getMessage());
            return "ERROR-CASE";
        }
    }
}